### ISSUE TITLE
是否考虑更新？

### ISSUE THREAD

**Issue by Bjoux2** [bigwiv/Biopython-cn#17]
当前英文文档“Last Update – 21 June 2018 (Biopython 1.72)”，应该有不少更新，是否考虑更新中文版本？

**Comment by lijax** [comment]
因目前工作不太相关，很难投入精力维护更新，如您有兴趣可组织更新下，建议以官方采用的tex文件格式进行翻译可能更合适

**Comment by zaneChou1** [comment]
最近我在学习biopython库时，发现英文版“Last Update – September 4, 2020 (Biopython 1.78)”与现有的中文版教程，代码块有许多差异，biopython的许多API已经变化。
我想基于现有的中文版教程去更新迭代，很乐于去帮助发展和维护这个项目。

**Comment by zaneChou1** [comment]
@lijax

**Comment by lijax** [comment]
@zaneChou1 非常欢迎，加你到维护列表了

**Comment by zaneChou1** [comment]
@lijax 谢谢信任，我计划先更新中文教程中的代码块，保持与最新的英文教程一致。

**Comment by lijax** [comment]
@zaneChou1  可以把英文也同步一份，与最新的保持一致，最好找几个同学一起更新哈

**Comment by zaneChou1** [comment]
是的，英文版应该同步更新。
欢迎对此感兴趣的开发者参与到biopython中文翻译版教程更新中。

**Comment by zaneChou1** [comment]
> @zaneChou1 可以把英文也同步一份，与最新的保持一致，最好找几个同学一起更新哈
我看到中文版，对应到网页端的中文教程 https://biopython-cn.readthedocs.io/zh_CN/latest/ ，更新后，网页端的中文教程是否会同步github库的更新

**Comment by lijax** [comment]
@zaneChou1 刚刚更新了webhook，push之后会更新到网页
