### ISSUE TITLE
更新同步到网页版Biopython中文教程

### ISSUE THREAD

**Issue by zaneChou1** [bigwiv/Biopython-cn#19]
我目前更新了本仓库Biopython中文和英文教程的第二章和第三章，见[PR 18](https://github.com/bigwiv/Biopython-cn/pull/18)，后续会更新其他章节。
请问是否可以同步Biopython-cn的更新内容到[Biopython中文网页教程](https://biopython-cn.readthedocs.io/)中。
@lijax

**Comment by lijax** [comment]
@zaneChou1 已更新，看看有没有问题，你有没有readthedocs账号，我你加一下

**Comment by zaneChou1** [comment]
@lijax 有的，readthedocs账号：zaneChou1

**Comment by lijax** [comment]
@zaneChou1 已添加

**Comment by zaneChou1** [comment]
ok 收到
